import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Loader2 } from "lucide-react";
import { authApi } from "@/api/authApi";
import { ApiError } from "@/api/client";
import { catalogApi, type CurriculumOption, type GradeOption, type SubjectOption } from "@/api/catalogApi";
import { getCountries, type CountryOption } from "@/api/countriesApi";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import AccountVerification from "@/components/AccountVerification";

const steps=["البيانات الشخصية","المؤهل والخبرة","التخصصات التعليمية","التجهيزات والتقييم","المرفقات والمراجعة"];
const yesNo=[{value:"true",label:"نعم"},{value:"false",label:"لا"}];
const initialValues:Record<string,string>={hasTeachingExperience:"false",hasOnlineTeachingExperience:"false",hasLaptop:"true",hasStableInternet:"true",hasGoodCamera:"true",hasMicrophone:"true",canProvideDemoSession:"true"};

export default function TeacherSignup(){
  const[step,setStep]=useState(0);const[values,setValues]=useState(initialValues);const[files,setFiles]=useState<Record<string,File|null>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[verificationEmail,setVerificationEmail]=useState("");
  const[countries,setCountries]=useState<CountryOption[]>([]);const[catalogsLoading,setCatalogsLoading]=useState(true);const[countriesError,setCountriesError]=useState("");
  const[curriculums,setCurriculums]=useState<CurriculumOption[]>([]);const[selectedCurriculum,setSelectedCurriculum]=useState("");const[grades,setGrades]=useState<GradeOption[]>([]);const[selectedGrades,setSelectedGrades]=useState<string[]>([]);const[subjects,setSubjects]=useState<Record<string,SubjectOption[]>>({});const[assignments,setAssignments]=useState<Record<string,string[]>>({});const[loadingGrades,setLoadingGrades]=useState(false);const[loadingSubjects,setLoadingSubjects]=useState<Record<string,boolean>>({});
  const set=(name:string,value:string)=>setValues(current=>({...current,[name]:value}));

  useEffect(()=>{const controller=new AbortController();Promise.all([getCountries(controller.signal).then(setCountries).catch(()=>setCountriesError("تعذر تحميل الدول.")),catalogApi.curriculums().then(result=>setCurriculums(result.data))]).catch(value=>setError((value as Error).message)).finally(()=>setCatalogsLoading(false));return()=>controller.abort();},[]);
  useEffect(()=>{if(!selectedCurriculum){setGrades([]);return;}setLoadingGrades(true);setSelectedGrades([]);setAssignments({});catalogApi.grades(selectedCurriculum).then(result=>setGrades(result.data.filter(grade=>grade.isActive!==false))).catch(value=>setError((value as ApiError).message)).finally(()=>setLoadingGrades(false));},[selectedCurriculum]);
  const toggleGrade=async(gradeId:string,checked:boolean)=>{if(!checked){setSelectedGrades(current=>current.filter(id=>id!==gradeId));setAssignments(current=>{const next={...current};delete next[gradeId];return next;});return;}setSelectedGrades(current=>[...current,gradeId]);if(subjects[gradeId])return;setLoadingSubjects(current=>({...current,[gradeId]:true}));try{const result=await catalogApi.subjects(gradeId);setSubjects(current=>({...current,[gradeId]:result.data}));}catch(value){setError((value as ApiError).message);}finally{setLoadingSubjects(current=>({...current,[gradeId]:false}));}};
  const toggleSubject=(gradeId:string,subjectId:string,checked:boolean)=>setAssignments(current=>({...current,[gradeId]:checked?[...(current[gradeId]||[]),subjectId]:(current[gradeId]||[]).filter(id=>id!==subjectId)}));
  const selectedCurriculumData=curriculums.find(item=>item.id===selectedCurriculum);
  const validStep=useMemo(()=>{if(step===0)return !!(values.fullName?.trim().length>=3&&values.email&&values.password?.length>=8&&values.phone&&values.nationality&&values.country);if(step===1)return !values.availableHoursPerWeek||Number(values.availableHoursPerWeek)>=1;if(step===2)return !!(selectedCurriculum&&selectedGrades.length&&selectedGrades.every(id=>(assignments[id]||[]).length));if(step===3)return !!values.computerSkillLevel;if(step===4)return values.termsAccepted==="true";return true;},[step,values,selectedCurriculum,selectedGrades,assignments]);
  const next=()=>{if(!validStep){setError(step===2?"اختر منهجًا وصفًا واحدًا على الأقل ومادة واحدة لكل صف.":"أكمل الحقول المطلوبة قبل المتابعة.");return;}setError("");setStep(current=>Math.min(current+1,steps.length-1));};
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!validStep)return;setBusy(true);setError("");try{const body=new FormData();Object.entries(values).forEach(([key,value])=>value&&body.append(key,value));body.append("curriculums",JSON.stringify([selectedCurriculum]));body.append("teacherAssignments",JSON.stringify(selectedGrades.map(grade=>({grade,subjects:assignments[grade]}))));Object.entries(files).forEach(([key,value])=>value&&body.append(key,value));const response=await authApi.registerTeacher(body);setVerificationEmail(response.data.email||values.email);}catch(value){const apiError=value as ApiError;setError(apiError.code==="EMAIL_ALREADY_EXISTS"?"البريد الإلكتروني مسجل بالفعل.":apiError.message);}finally{setBusy(false);}};

  if(verificationEmail)return <AccountVerification email={verificationEmail} onVerified={()=>{window.location.href=`/portal/login?email=${encodeURIComponent(verificationEmail)}&verified=1`;}}/>;

  return <main className="min-h-screen bg-hero-gradient flex items-center justify-center py-8 px-4" dir="rtl"><Card className="max-w-4xl w-full mx-auto min-h-[640px] flex flex-col"><CardHeader><CardTitle>التسجيل كمعلم</CardTitle><div className="grid grid-cols-5 gap-2 pt-4">{steps.map((title,index)=><div key={title} className="text-center"><div className={`h-2 rounded-full ${index<=step?"bg-secondary":"bg-muted"}`}/><span className={`hidden md:block text-xs mt-2 ${index===step?"font-bold":"text-muted-foreground"}`}>{title}</span></div>)}</div></CardHeader><CardContent className="flex-1 flex flex-col"><form onSubmit={submit} className="flex-1 flex flex-col">
  <div className="flex-1 flex flex-col justify-center space-y-5">
    {error&&<div role="alert" className="rounded-xl bg-destructive/10 text-destructive p-3 text-sm">{error}</div>}
    {step===0&&<div className="grid sm:grid-cols-2 gap-4"><Field label="الاسم الكامل *"><Input value={values.fullName||""} onChange={e=>set("fullName",e.target.value)}/></Field><Field label="البريد الإلكتروني *"><Input type="email" dir="ltr" value={values.email||""} onChange={e=>set("email",e.target.value)}/></Field><Field label="كلمة المرور *"><Input type="password" dir="ltr" minLength={8} value={values.password||""} onChange={e=>set("password",e.target.value)}/></Field><Field label="رقم الهاتف *"><Input dir="ltr" value={values.phone||""} onChange={e=>set("phone",e.target.value)}/></Field><Field label="رقم واتساب"><Input dir="ltr" value={values.whatsapp||""} onChange={e=>set("whatsapp",e.target.value)}/></Field><CountrySelect label="الجنسية *" value={values.nationality||""} loading={catalogsLoading} countries={countries} onChange={value=>set("nationality",value)}/><CountrySelect label="الدولة *" value={values.country||""} loading={catalogsLoading} countries={countries} onChange={value=>set("country",value)}/><Field label="المدينة"><Input value={values.city||""} onChange={e=>set("city",e.target.value)}/></Field>{countriesError&&<p className="sm:col-span-2 text-sm text-destructive">{countriesError}</p>}</div>}
    {step===1&&<div className="grid sm:grid-cols-2 gap-4"><Field label="المؤهل"><Input value={values.degree||""} onChange={e=>set("degree",e.target.value)}/></Field><Field label="التخصص"><Input value={values.specialization||""} onChange={e=>set("specialization",e.target.value)}/></Field><Field label="اسم المؤسسة التعليمية"><Input value={values.institutionName||""} onChange={e=>set("institutionName",e.target.value)}/></Field><Field label="سنة التخرج"><Input type="number" min="1950" max={new Date().getFullYear()} value={values.graduationYear||""} onChange={e=>set("graduationYear",e.target.value)}/></Field><SelectField label="التقدير" value={values.graduationGrade||""} onChange={value=>set("graduationGrade",value)} options={[{value:"excellent",label:"ممتاز"},{value:"very-good",label:"جيد جدًا"},{value:"good",label:"جيد"},{value:"pass",label:"مقبول"}]}/><SelectField label="هل لديك خبرة تدريس؟" value={values.hasTeachingExperience} onChange={value=>set("hasTeachingExperience",value)} options={yesNo}/><SelectField label="هل لديك خبرة بالتدريس عن بُعد؟" value={values.hasOnlineTeachingExperience} onChange={value=>set("hasOnlineTeachingExperience",value)} options={yesNo}/><Field label="الساعات المتاحة أسبوعيًا"><Input type="number" min="1" value={values.availableHoursPerWeek||""} onChange={e=>set("availableHoursPerWeek",e.target.value)}/></Field></div>}
    {step===2&&<div className="space-y-5"><SelectField label="المنهج الذي ترغب في تدريسه *" value={selectedCurriculum} onChange={setSelectedCurriculum} loading={catalogsLoading} options={curriculums.map(item=>({value:item.id,label:`${item.name} — ${item.registrationMode==="egyptian"?"مصري":"سعودي/خليجي"}`}))}/>{selectedCurriculum&&<div><h3 className="font-bold mb-3">اختر الصفوف والمواد لكل صف</h3>{loadingGrades?<Loader/>:grades.length===0?<p className="text-muted-foreground">لا توجد صفوف نشطة لهذا المنهج.</p>:<div className="space-y-3">{grades.map(grade=><div key={grade.id} className="rounded-xl border p-4"><label className="flex items-center gap-3 font-semibold"><Checkbox checked={selectedGrades.includes(grade.id)} onCheckedChange={checked=>void toggleGrade(grade.id,checked===true)}/>{grade.name}</label>{selectedGrades.includes(grade.id)&&<div className="mt-4 pr-7"><p className="text-sm text-muted-foreground mb-2">المواد التي تستطيع تدريسها:</p>{loadingSubjects[grade.id]?<Loader/>:<div className="flex flex-wrap gap-3">{(subjects[grade.id]||[]).map(subject=><label key={subject.id} className="flex items-center gap-2 rounded-lg bg-muted px-3 py-2 text-sm"><Checkbox checked={(assignments[grade.id]||[]).includes(subject.id)} onCheckedChange={checked=>toggleSubject(grade.id,subject.id,checked===true)}/>{subject.name}</label>)}</div>}</div>}</div>)}</div>}</div>}</div>}
    {step===3&&<div className="grid sm:grid-cols-2 gap-4"><SelectField label="مستوى استخدام الكمبيوتر *" value={values.computerSkillLevel||""} onChange={value=>set("computerSkillLevel",value)} options={[{value:"excellent",label:"ممتاز"},{value:"very-good",label:"جيد جدًا"},{value:"good",label:"جيد"}]}/>{[["hasLaptop","هل لديك حاسوب؟"],["hasStableInternet","هل الإنترنت مستقر؟"],["hasGoodCamera","هل لديك كاميرا جيدة؟"],["hasMicrophone","هل لديك ميكروفون؟"],["canProvideDemoSession","هل يمكنك تقديم حصة تجريبية؟"]].map(([name,label])=><SelectField key={name} label={label} value={values[name]} onChange={value=>set(name,value)} options={yesNo}/>)}<Field label="رابط الفيديو التعريفي"><Input dir="ltr" type="url" value={values.introVideoUrl||""} onChange={e=>set("introVideoUrl",e.target.value)}/></Field><Field label="لماذا تريد الانضمام؟"><Textarea value={values.joiningReason||""} onChange={e=>set("joiningReason",e.target.value)}/></Field><div className="sm:col-span-2"><Field label="كيف تتعامل مع الطالب الضعيف؟"><Textarea value={values.weakStudentHandling||""} onChange={e=>set("weakStudentHandling",e.target.value)}/></Field></div></div>}
    {step===4&&<div className="space-y-5"><div className="grid sm:grid-cols-3 gap-4">{[["cv","السيرة الذاتية"],["certificate","الشهادة"],["identityDocument","إثبات الهوية"]].map(([name,label])=><Field key={name} label={label}><Input type="file" onChange={e=>setFiles(current=>({...current,[name]:e.target.files?.[0]||null}))}/></Field>)}</div><div className="rounded-xl bg-muted p-4 text-sm space-y-1"><p><strong>المنهج:</strong> {selectedCurriculumData?.name}</p><p><strong>الصفوف المختارة:</strong> {selectedGrades.length}</p><p><strong>إجمالي المواد:</strong> {Object.values(assignments).reduce((total,list)=>total+list.length,0)}</p></div><label className="flex items-center gap-3"><Checkbox checked={values.termsAccepted==="true"} onCheckedChange={checked=>set("termsAccepted",checked===true?"true":"false")}/>أوافق على الشروط والإقرار بصحة البيانات.</label></div>}
  </div>
    <div className="flex justify-between border-t pt-5 mt-6"><div>{step>0?<Button type="button" variant="outline" onClick={()=>{setError("");setStep(current=>current-1);}}><ArrowRight className="h-4 w-4 ml-2"/>السابق</Button>:<Button type="button" variant="outline" asChild><Link to="/portal/login">إلغاء</Link></Button>}</div>{step<steps.length-1?<Button type="button" onClick={next}>التالي<ArrowLeft className="h-4 w-4 mr-2"/></Button>:<Button disabled={busy||!validStep} type="submit">{busy?<><Loader2 className="h-4 w-4 ml-2 animate-spin"/>جاري الإرسال...</>:"إرسال طلب التسجيل"}</Button>}</div>
  </form></CardContent></Card></main>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm space-y-1.5 block"><span>{label}</span>{children}</label>}
function SelectField({label,value,onChange,options,loading=false}:{label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string}[];loading?:boolean}){return <Field label={label}><Select value={value} onValueChange={onChange} disabled={loading}><SelectTrigger><SelectValue placeholder={loading?"جاري التحميل...":"اختر"}/></SelectTrigger><SelectContent>{options.map(option=><SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></Field>}
function CountrySelect({label,value,onChange,countries,loading}:{label:string;value:string;onChange:(value:string)=>void;countries:CountryOption[];loading:boolean}){return <Field label={label}><Select value={value} onValueChange={onChange} disabled={loading}><SelectTrigger><SelectValue placeholder={loading?"جاري التحميل...":"اختر"}/></SelectTrigger><SelectContent>{countries.map(country=><SelectItem key={country.code} value={country.name}>{country.flag} {country.name}</SelectItem>)}</SelectContent></Select></Field>}
function Loader(){return <div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>جاري التحميل...</div>}
