import { FormEvent,useCallback,useEffect,useState } from "react";
import { AlertTriangle,Check,ChevronLeft,ChevronRight,Clipboard,Eye,Loader2,RefreshCw,Search,X } from "lucide-react";
import { toast } from "sonner";
import { clientErrorsAdminApi,type AdminClientError,type ClientErrorListParams,type ClientErrorStatus } from "@/api/clientErrorsAdminApi";
import DashboardLayout from "@/layouts/DashboardLayout";
import { useLanguage } from "@/i18n/LanguageContext";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select"; import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet"; import { Skeleton } from "@/components/ui/skeleton"; import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
const phases=["preparing-request","validation","compressing-files","uploading","waiting-response","success-handling","unknown"];
const phaseLabel:Record<string,string>={"preparing-request":"تجهيز الطلب",validation:"التحقق","compressing-files":"ضغط الملفات",uploading:"رفع الملفات","waiting-response":"انتظار الاستجابة","success-handling":"معالجة النجاح",unknown:"غير معروف"};
const statusLabel={new:"جديد",resolved:"تم الحل",ignored:"متجاهل"},statusStyle={new:"border-amber-300 bg-amber-50 text-amber-800",resolved:"border-emerald-300 bg-emerald-50 text-emerald-800",ignored:"border-slate-300 bg-slate-50 text-slate-700"};
const human=(v?:string)=>v?v.split("-").map(x=>x[0].toUpperCase()+x.slice(1)).join(" "):"—";
const when=(v:string|undefined,l:string)=>v?new Intl.DateTimeFormat(l,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const elapsed=(v?:number)=>v===undefined?"—":Math.round(v/1000)>=60?`${Math.floor(Math.round(v/1000)/60)}m ${Math.round(v/1000)%60}s`:`${Math.round(v/1000)}s`;
const Status=({value}:{value:ClientErrorStatus})=><Badge variant="outline" className={statusStyle[value]}>{statusLabel[value]}</Badge>;
const Detail=({label,value}:{label:string;value:unknown})=><div className="rounded-lg border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-sm font-medium">{value===undefined||value===null||value===""?"—":String(value)}</p></div>;
function Filter({label,value,all,options,onChange}:{label:string;value?:string;all:string;options:string[][];onChange:(v?:string)=>void}){return <div className="space-y-1"><Label>{label}</Label><Select value={value||"all"} onValueChange={v=>onChange(v==="all"?undefined:v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{all}</SelectItem>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>}
export default function ClientErrorsAdmin(){const {isArabic}=useLanguage(),locale=isArabic?"ar-SA-u-ca-gregory":"en-US";const [filters,setFilters]=useState<ClientErrorListParams>({page:1,limit:20}),[search,setSearch]=useState(""),[rows,setRows]=useState<AdminClientError[]>([]),[total,setTotal]=useState<number>(),[pages,setPages]=useState<number>(),[next,setNext]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<AdminClientError|null>(null),[detailLoading,setDetailLoading]=useState(false),[updating,setUpdating]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await clientErrorsAdminApi.list(filters);setRows(r.data);setTotal(r.total);setPages(r.totalPages);setNext(r.hasNextPage)}catch{setError("تعذر تحميل أخطاء التطبيقات.")}finally{setLoading(false)}},[filters]);useEffect(()=>{void load()},[load]);
 const change=(k:keyof ClientErrorListParams,v?:string|number)=>setFilters(f=>({...f,[k]:v||undefined,page:k==="page"?Number(v):1}));const submit=(e:FormEvent)=>{e.preventDefault();change("search",search.trim())};const clear=()=>{setSearch("");setFilters({page:1,limit:20})};
 const open=async(r:AdminClientError)=>{setSelected(r);setDetailLoading(true);try{setSelected(await clientErrorsAdminApi.get(r.id))}catch{toast.error("تعذر تحميل تفاصيل الخطأ.")}finally{setDetailLoading(false)}};
 const update=async(status:ClientErrorStatus)=>{if(!selected)return;setUpdating(true);try{const r=await clientErrorsAdminApi.updateStatus(selected.id,status),merged={...selected,...r,status};setSelected(merged);setRows(xs=>xs.map(x=>x.id===merged.id?merged:x));toast.success("تم تحديث حالة الخطأ.")}catch{toast.error("تعذر تحديث الحالة.")}finally{setUpdating(false)}};
 const copy=async(v?:string)=>{if(v){await navigator.clipboard.writeText(v);toast.success("تم النسخ.")}};const sources=[...new Set(rows.map(x=>x.source).filter(Boolean))] as string[],filtered=Boolean(filters.search||filters.source||filters.phase||filters.errorCode||filters.status||filters.from||filters.to);
 return <DashboardLayout><div className="mx-auto max-w-7xl space-y-5" dir="rtl"><div><h1 className="flex items-center gap-2 text-3xl font-bold"><AlertTriangle className="h-7 w-7 text-primary"/>أخطاء التطبيقات</h1><p className="mt-1 text-muted-foreground">متابعة وتشخيص الأخطاء المرسلة من تطبيقات بنان.</p></div>{total!==undefined&&<Card className="max-w-xs"><CardContent className="p-4"><p className="text-sm text-muted-foreground">إجمالي الأخطاء</p><p className="text-2xl font-bold">{total.toLocaleString(locale)}</p></CardContent></Card>}
 <Card><CardContent className="space-y-4 p-4"><form onSubmit={submit} className="flex gap-2"><div className="relative flex-1"><Search className="absolute right-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input aria-label="بحث بالبريد أو الهاتف" className="pr-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="البريد الإلكتروني أو الهاتف"/></div><Button>بحث</Button></form><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><Filter label="المصدر" value={filters.source} all="كل المصادر" options={sources.map(v=>[v,human(v)])} onChange={v=>change("source",v)}/><Filter label="المرحلة" value={filters.phase} all="كل المراحل" options={phases.map(v=>[v,phaseLabel[v]])} onChange={v=>change("phase",v)}/><div className="space-y-1"><Label>كود الخطأ</Label><Input aria-label="كود الخطأ" value={filters.errorCode||""} onChange={e=>change("errorCode",e.target.value)}/></div><Filter label="الحالة" value={filters.status} all="كل الحالات" options={Object.entries(statusLabel)} onChange={v=>change("status",v)}/><div className="space-y-1"><Label htmlFor="from">من</Label><Input id="from" type="date" value={filters.from||""} onChange={e=>change("from",e.target.value)}/></div><div className="space-y-1"><Label htmlFor="to">إلى</Label><Input id="to" type="date" value={filters.to||""} onChange={e=>change("to",e.target.value)}/></div><Button type="button" variant="outline" className="self-end" onClick={clear}><X className="ml-1 h-4 w-4"/>مسح الفلاتر</Button></div></CardContent></Card>
 <Card><CardContent className="p-0">{loading?<div aria-label="جاري التحميل" className="space-y-3 p-6">{[1,2,3,4].map(n=><Skeleton key={n} className="h-12"/>)}</div>:error?<div role="alert" className="grid place-items-center gap-3 p-12"><p>{error}</p><Button variant="outline" onClick={()=>void load()}><RefreshCw className="ml-2 h-4 w-4"/>إعادة المحاولة</Button></div>:!rows.length?<div className="p-12 text-center text-muted-foreground">{filtered?"لا توجد نتائج مطابقة للفلاتر":"لا توجد أخطاء مسجلة"}</div>:<><div className="hidden overflow-x-auto lg:block"><Table><TableHeader><TableRow>{["الوقت","المستخدم","المصدر","المرحلة","الخطأ","الجهاز","الملفات","الحالة","الإجراء"].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id} className="cursor-pointer" onClick={()=>void open(r)}><TableCell className="whitespace-nowrap text-xs">{when(r.createdAt,locale)}</TableCell><TableCell><span className="block font-medium">{r.name||"—"}</span><small className="block text-muted-foreground" dir="ltr">{r.email||"—"}</small><small className="block text-muted-foreground" dir="ltr">{r.phone||"—"}</small></TableCell><TableCell>{human(r.source)}</TableCell><TableCell>{phaseLabel[r.phase||""]||human(r.phase)}</TableCell><TableCell className={r.errorCode==="NETWORK_ERROR"||r.errorCode==="TIMEOUT"?"font-semibold text-amber-700":""}>{r.errorCode||"—"}</TableCell><TableCell>{[r.os,r.browser].filter(Boolean).join(" / ")||"—"}</TableCell><TableCell className="whitespace-nowrap">{r.filesCount??"—"}{r.totalSizeMB!==undefined&&` · ${r.totalSizeMB.toFixed(2)} MB`}</TableCell><TableCell><Status value={r.status}/></TableCell><TableCell><Button size="sm" variant="ghost" onClick={e=>{e.stopPropagation();void open(r)}}><Eye className="ml-1 h-4 w-4"/>عرض</Button></TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 p-3 lg:hidden">{rows.map(r=><button key={r.id} onClick={()=>void open(r)} className="rounded-lg border p-4 text-right"><div className="flex justify-between"><span><strong className="block">{r.name||"—"}</strong><small dir="ltr">{r.email||r.phone||"—"}</small></span><Status value={r.status}/></div><p className="mt-3 font-mono">{r.errorCode||"—"}</p><small>{human(r.source)} · {human(r.phase)}</small></button>)}</div></>}
 {!loading&&!error&&<div className="flex items-center justify-between border-t p-4"><Select value={String(filters.limit)} onValueChange={v=>change("limit",Number(v))}><SelectTrigger aria-label="عدد النتائج" className="w-24"><SelectValue/></SelectTrigger><SelectContent>{[20,50,100].map(n=><SelectItem key={n} value={String(n)}>{n}</SelectItem>)}</SelectContent></Select><span>صفحة {filters.page}{pages?` / ${pages}`:""}</span><div className="flex gap-2"><Button aria-label="السابق" size="icon" variant="outline" disabled={filters.page<=1} onClick={()=>change("page",filters.page-1)}><ChevronRight/></Button><Button aria-label="التالي" size="icon" variant="outline" disabled={!next} onClick={()=>change("page",filters.page+1)}><ChevronLeft/></Button></div></div>}</CardContent></Card>
 <Sheet open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><SheetContent side="left" className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>تفاصيل الخطأ</SheetTitle><SheetDescription>{selected?.id}</SheetDescription></SheetHeader>{detailLoading?<Loader2 className="mx-auto mt-20 animate-spin"/>:selected&&<div className="mt-6 space-y-5"><Section title="المستخدم"><Detail label="Name" value={selected.name}/><Detail label="Email" value={selected.email}/><Detail label="Phone" value={selected.phone}/></Section><Section title="الخطأ"><Detail label="Source" value={human(selected.source)}/><Detail label="Platform" value={human(selected.platform)}/><Detail label="Phase" value={human(selected.phase)}/><div className="relative"><Detail label="Error Code" value={selected.errorCode}/><Button aria-label="نسخ كود الخطأ" className="absolute left-1 top-1" size="icon" variant="ghost" onClick={()=>void copy(selected.errorCode)}><Clipboard/></Button></div><div className="relative col-span-2 min-h-28 rounded-lg border bg-muted/20 p-3 pl-12"><p className="text-xs text-muted-foreground">Message</p><p className="mt-2 whitespace-pre-wrap break-words" dir="ltr">{selected.message||"—"}</p><Button aria-label="نسخ الرسالة" className="absolute left-1 top-1" size="icon" variant="ghost" onClick={()=>void copy(selected.message)}><Clipboard/></Button></div></Section><Section title="الجهاز"><Detail label="Browser" value={selected.browser}/><Detail label="OS" value={selected.os}/></Section><Section title="التسجيل والرفع"><Detail label="Files count" value={selected.filesCount}/><Detail label="Total size" value={selected.totalSizeMB===undefined?undefined:`${selected.totalSizeMB.toFixed(2)} MB`}/><Detail label="Duration" value={elapsed(selected.durationMs)}/><Detail label="Last step" value={selected.lastStep}/></Section><Section title="النظام"><Detail label="Created at" value={when(selected.createdAt,locale)}/><Detail label="Status" value={statusLabel[selected.status]}/><Detail label="Resolved at" value={when(selected.resolvedAt,locale)}/><Detail label="Resolved by" value={typeof selected.resolvedBy==="string"?selected.resolvedBy:selected.resolvedBy?.fullName||selected.resolvedBy?.email}/></Section><div className="flex flex-wrap gap-2 border-t pt-4"><Button disabled={updating||selected.status==="resolved"} onClick={()=>void update("resolved")}><Check className="ml-1"/>تحديد كمحلول</Button><Button variant="outline" disabled={updating||selected.status==="ignored"} onClick={()=>void update("ignored")}><X className="ml-1"/>تجاهل</Button><Button variant="outline" disabled={updating||selected.status==="new"} onClick={()=>void update("new")}><RefreshCw className="ml-1"/>إعادة الفتح</Button></div></div>}</SheetContent></Sheet>
 </div></DashboardLayout>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h3 className="mb-2 font-semibold">{title}</h3><div className="grid grid-cols-2 gap-2">{children}</div></section>}
